[15062025 23:17:57] modules /code/src/modules.c:197-message: new module lib/dionaea/curl.so 0x561286b9a670 fn 0x7f75aac2e8d6
[15062025 23:17:57] curl /code/modules/curl/module.c:593-debug: curl_new
[15062025 23:17:57] curl /code/modules/curl/module.c:638-info: curl version 7.58.0 features:c-ares,idn,ipv6,largefile,ntlm,spnego,ssl,libz protocols:dict,file,ftp,ftps,gopher,http,https,imap,imaps,ldap,ldaps,pop3,pop3s,rtmp,rtsp,smb,smbs,smtp,smtps,telnet,tftp 
[15062025 23:17:57] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.download.offer cb 0x7f75aac2e70d ctx (nil)
[15062025 23:17:57] incident /code/src/incident.c:167-debug: ihandler 0x561286ba0170 pattern dionaea.download.offer cb 0x7f75aac2e70d ctx (nil)
[15062025 23:17:57] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.upload.request cb 0x7f75aac2e70d ctx (nil)
[15062025 23:17:57] incident /code/src/incident.c:167-debug: ihandler 0x561286b9f520 pattern dionaea.upload.request cb 0x7f75aac2e70d ctx (nil)
[15062025 23:17:57] modules /code/src/modules.c:197-message: new module lib/dionaea/python.so 0x561286b9c1c0 fn 0x7f75a5881868
[15062025 23:17:57] python /code/modules/python/module.c:324-debug: new /code/modules/python/module.c 0x561286b42810
[15062025 23:17:57] python /code/modules/python/module.c:328-debug: Python Interpreter /usr/bin/python3.6
[15062025 23:17:57] python /code/modules/python/module.c:366-debug: running sys.path.insert(0, 'lib/dionaea/python') default
[15062025 23:17:57] services /dionaea/services.py:114-info: Initializing services ...
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.blackhole
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.cmd
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.core
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.echo
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.emu
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.emu_scripts
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.exception
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.fail2ban
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.ftp
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.ftp_download
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.hpfeeds
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.http
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.ihandlers
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.log
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.log_db_sql
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.log_incident
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.log_json
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.logsql
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.memcache
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mirror
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mongo
[15062025 23:17:57] asn1fields /dionaea/smb/include/asn1fields.py:156-debug: i2s {0: 'completed', 1: 'incomplete', 2: 'reject'}
[15062025 23:17:57] asn1fields /dionaea/smb/include/asn1fields.py:157-debug: s2i {'completed': 0, 'incomplete': 1, 'reject': 2}
[15062025 23:17:57] asn1fields /dionaea/smb/include/asn1fields.py:338-debug: self.choice {48: <class 'dionaea.smb.include.gssapifields.NegTokenInit'>}
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mqtt
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mssql
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mysql
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.ndrlib
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.nfq
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.p0f
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.pptp
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.printer
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.s3
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.services
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.sip
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.smb
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.store
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.submit_http
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.submit_http_post
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.tftp
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.upnp
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.util
[15062025 23:17:57] dionaea /dionaea/__init__.py:148-info: Import module dionaea.virustotal
[15062025 23:17:57] ihandlers /dionaea/ihandlers.py:25-info: Load iHandlers
[15062025 23:17:57] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.*.mkshell cb 0x7f75a5880890 ctx (nil)
[15062025 23:17:57] incident /code/src/incident.c:167-debug: ihandler 0x56128713c610 pattern dionaea.*.mkshell cb 0x7f75a5880890 ctx (nil)
[15062025 23:17:57] modules /code/src/modules.c:197-message: new module lib/dionaea/emu.so 0x561286b9cf10 fn 0x7f75a4b93c19
[15062025 23:17:57] emu /code/modules/emu/module.c:37-debug: emu_new
[15062025 23:17:57] dionaea /code/src/dionaea.c:669-debug: Creating processors tree
[15062025 23:17:57] processor /code/src/processor.c:25-debug: processors_tree_create - processor: filter_streamdumper
[15062025 23:17:57] processor /code/src/processor.c:707-debug: Key file does not have key “config.allow.0.protocols” in group “processor.filter_streamdumper”
[15062025 23:17:57] processor /code/src/processor.c:744-debug: Key file does not have key “config.deny.0.types” in group “processor.filter_streamdumper”
[15062025 23:17:57] processor /code/src/processor.c:629-debug: Dumping filter rules ...
[15062025 23:17:57] processor /code/src/processor.c:638-debug: allow:
[15062025 23:17:57] processor /code/src/processor.c:645-debug: - protocol  
[15062025 23:17:57] processor /code/src/processor.c:645-debug: - type  
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - accept
[15062025 23:17:57] processor /code/src/processor.c:645-debug: - protocol  
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - ftpctrl
[15062025 23:17:57] processor /code/src/processor.c:645-debug: - type  
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - connect
[15062025 23:17:57] processor /code/src/processor.c:638-debug: deny:
[15062025 23:17:57] processor /code/src/processor.c:645-debug: - protocol  
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - ftpdata
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - ftpdatacon
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - xmppclient
[15062025 23:17:57] processor /code/src/processor.c:645-debug: - type  
[15062025 23:17:57] processor /code/src/processor.c:25-debug: processors_tree_create - processor: streamdumper
[15062025 23:17:57] processor /code/src/processor.c:339-info: var/lib/dionaea/bistreams/2025-06-15/ <-> var/lib/dionaea/bistreams/%Y-%m-%d/
[15062025 23:17:57] dionaea /code/src/dionaea.c:676-debug: processo: filter_streamdumper
[15062025 23:17:57] processor /code/src/processor.c:25-debug: processors_tree_create - processor: filter_emu
[15062025 23:17:57] processor /code/src/processor.c:718-debug: Key file does not have key “config.allow.0.types” in group “processor.filter_emu”
[15062025 23:17:57] processor /code/src/processor.c:629-debug: Dumping filter rules ...
[15062025 23:17:57] processor /code/src/processor.c:638-debug: allow:
[15062025 23:17:57] processor /code/src/processor.c:645-debug: - protocol  
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - smbd
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - epmapper
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - nfqmirrord
[15062025 23:17:57] processor /code/src/processor.c:654-debug:   - mssqld
[15062025 23:17:57] processor /code/src/processor.c:645-debug: - type  
[15062025 23:17:57] processor /code/src/processor.c:25-debug: processors_tree_create - processor: emu
[15062025 23:17:57] emu /code/modules/emu/detect.c:39-debug: proc_emu_ctx_cfg_new node
[15062025 23:17:57] emu /code/modules/emu/detect.c:86-debug:  files 3 filesize 524288 sockets 3 steps 1073741824 idle 30.000000 listen 30.000000 sustain 120.000000 cpu 120.000000 
[15062025 23:17:57] dionaea /code/src/dionaea.c:676-debug: processo: filter_emu
[15062025 23:17:57] processor /code/src/processor.c:71-debug:      filter
[15062025 23:17:57] processor /code/src/processor.c:71-debug:          streamdumper
[15062025 23:17:57] processor /code/src/processor.c:71-debug:      filter
[15062025 23:17:57] processor /code/src/processor.c:71-debug:          emu
[15062025 23:17:57] dionaea /code/src/dionaea.c:726-debug: old umask -----w--w-
[15062025 23:17:57] dionaea /code/src/dionaea.c:727-debug: new umask -----w--w-
[15062025 23:17:57] dionaea /code/src/dionaea.c:742-info: Using 1048576 as limit for fds
[15062025 23:17:57] modules /code/src/modules.c:184-message: start module 0x561286b9a670
[15062025 23:17:57] modules /code/src/modules.c:184-message: start module 0x561286b9c1c0
[15062025 23:17:57] python /code/modules/python/module.c:293-info: start /code/modules/python/module.c
[15062025 23:17:57] python /code/modules/python/module.c:303-info: start dionaea.log 0x561286b917b0 0x7f75a45ffae8
[15062025 23:17:57] python /code/modules/python/module.c:303-info: start dionaea.services 0x561286b91cf0 0x7f75a45ffcc8
[15062025 23:17:57] services /dionaea/services.py:164-info: Starting services ...
[15062025 23:17:57] services /dionaea/services.py:32-info: Starting services on interface eth0 ...
[15062025 23:17:57] services /dionaea/services.py:34-info: Bind interfaces to address '172.18.0.4' ...
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561286e33e60 addr 172.18.0.4 port 1433 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561286e33e60 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561286e33e60
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 9 172.18.0.4:1433
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:1433'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b96050
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b96050 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561286e33e60
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561286e345f0 addr 172.18.0.4 port 27017 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561286e345f0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561286e345f0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 10 172.18.0.4:27017
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:27017'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b96450
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b96450 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561286e345f0
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128713c640 addr 172.18.0.4 port 3306 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128713c640 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128713c640
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 11 172.18.0.4:3306
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:3306'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b96b10
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b96b10 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128713c640
[15062025 23:17:57] http /dionaea/http.py:232-debug: http test
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:490-warning: Root path 'var/lib/dionaea/http/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128713d540 addr 172.18.0.4 port 80 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128713d540 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128713d540
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 12 172.18.0.4:80
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:80'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b7f400
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b7f400 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128713d540
[15062025 23:17:57] http /dionaea/http.py:232-debug: http test
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:490-warning: Root path 'var/lib/dionaea/http/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287141f90 addr 172.18.0.4 port 443 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287141f90 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287141f90
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 15 172.18.0.4:443
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:443'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection_tls.c:158-debug: connection_tls_mkcert con 0x561287141f90
[15062025 23:17:57] ftp /dionaea/ftp.py:167-debug: ftp test
[15062025 23:17:57] ftp /dionaea/ftp.py:149-critical: The basedir 'var/lib/dionaea/ftp/root' is not a directory
[15062025 23:17:57] tftp /dionaea/tftp.py:54-critical: Root path 'var/lib/dionaea/tftp/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871428e0 addr 172.18.0.4 port 69 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871428e0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 16 172.18.0.4:69
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '172.18.0.4' node '172.18.0.4:69'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287143070 addr 172.18.0.4 port 1723 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287143070 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287143070
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 17 172.18.0.4:1723
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:1723'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b8b5d0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b8b5d0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287143070
[15062025 23:17:57] memcache /dionaea/memcache/__init__.py:45-debug: start memcache
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287144430 addr 172.18.0.4 port 11211 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287144430 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287144430
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 18 172.18.0.4:11211
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:11211'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b8b150
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b8b150 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287144430
[15062025 23:17:57] printer /dionaea/printer.py:36-critical: The PCL output directory 'var/lib/dionaea/binaries/' is not a directory
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287154320 addr 172.18.0.4 port 23 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287154320 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287154320
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 19 172.18.0.4:23
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:23'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b9e2b0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b9e2b0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287154320
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287154ab0 addr 172.18.0.4 port 53 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287154ab0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 20 172.18.0.4:53
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '172.18.0.4' node '172.18.0.4:53'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287154ab0 len 20
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287155240 addr 172.18.0.4 port 53 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287155240 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287155240
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 21 172.18.0.4:53
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:53'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b96bd0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b96bd0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287155240
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871559d0 addr 172.18.0.4 port 123 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871559d0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 22 172.18.0.4:123
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '172.18.0.4' node '172.18.0.4:123'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871559d0 len 20
[15062025 23:17:57] sip /dionaea/sip/__init__.py:568-debug: <dionaea.sip.SipSession object at 0x7f75a1585b88> __init__
[15062025 23:17:57] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 88, in __init__
    self._conn = sqlite3.connect(self.users)
sqlite3.OperationalError: unable to open database file
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128714a030 addr 172.18.0.4 port 1883 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128714a030 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128714a030
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 23 172.18.0.4:1883
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:1883'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b7d5e0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b7d5e0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128714a030
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128716d400 addr 172.18.0.4 port 1900 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128716d400
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 24 172.18.0.4:1900
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '172.18.0.4' node '172.18.0.4:1900'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128716d400 len 20
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128716db90 addr 172.18.0.4 port 445 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128716db90 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128716db90
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 25 172.18.0.4:445
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:445'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b8ab00
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b8ab00 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128716db90
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128716e320 addr 172.18.0.4 port 42 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128716e320 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128716e320
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 26 172.18.0.4:42
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:42'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b7e800
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b7e800 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128716e320
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128716eab0 addr 172.18.0.4 port 135 iface eth0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128716eab0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128716eab0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 27 172.18.0.4:135
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '172.18.0.4' node '172.18.0.4:135'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b7f1c0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b7f1c0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128716eab0
[15062025 23:17:57] services /dionaea/services.py:32-info: Starting services on interface lo ...
[15062025 23:17:57] services /dionaea/services.py:34-info: Bind interfaces to address '127.0.0.1' ...
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128716f240 addr 127.0.0.1 port 1433 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128716f240 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128716f240
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 28 127.0.0.1:1433
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:1433'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b7fc40
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b7fc40 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128716f240
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128716f9d0 addr 127.0.0.1 port 27017 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128716f9d0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128716f9d0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 29 127.0.0.1:27017
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:27017'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b80180
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b80180 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128716f9d0
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287170160 addr 127.0.0.1 port 3306 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287170160 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287170160
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 30 127.0.0.1:3306
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:3306'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b806c0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b806c0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287170160
[15062025 23:17:57] http /dionaea/http.py:232-debug: http test
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:490-warning: Root path 'var/lib/dionaea/http/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871708f0 addr 127.0.0.1 port 80 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871708f0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871708f0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 31 127.0.0.1:80
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:80'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b810c0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b810c0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5612871708f0
[15062025 23:17:57] http /dionaea/http.py:232-debug: http test
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:490-warning: Root path 'var/lib/dionaea/http/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287171520 addr 127.0.0.1 port 443 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287171520 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287171520
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 32 127.0.0.1:443
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:443'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection_tls.c:158-debug: connection_tls_mkcert con 0x561287171520
[15062025 23:17:57] ftp /dionaea/ftp.py:167-debug: ftp test
[15062025 23:17:57] ftp /dionaea/ftp.py:149-critical: The basedir 'var/lib/dionaea/ftp/root' is not a directory
[15062025 23:17:57] tftp /dionaea/tftp.py:54-critical: Root path 'var/lib/dionaea/tftp/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287181d90 addr 127.0.0.1 port 69 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287181d90
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 33 127.0.0.1:69
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '127.0.0.1' node '127.0.0.1:69'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287171cb0 addr 127.0.0.1 port 1723 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287171cb0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287171cb0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 34 127.0.0.1:1723
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:1723'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b87ac0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b87ac0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287171cb0
[15062025 23:17:57] memcache /dionaea/memcache/__init__.py:45-debug: start memcache
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287172440 addr 127.0.0.1 port 11211 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287172440 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287172440
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 35 127.0.0.1:11211
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:11211'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b87f40
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b87f40 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287172440
[15062025 23:17:57] printer /dionaea/printer.py:36-critical: The PCL output directory 'var/lib/dionaea/binaries/' is not a directory
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287173c10 addr 127.0.0.1 port 23 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287173c10 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287173c10
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 36 127.0.0.1:23
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:23'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286e921c0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286e921c0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287173c10
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871743a0 addr 127.0.0.1 port 53 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871743a0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 37 127.0.0.1:53
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '127.0.0.1' node '127.0.0.1:53'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871743a0 len 20
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287174b30 addr 127.0.0.1 port 53 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287174b30 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287174b30
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 38 127.0.0.1:53
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:53'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b89400
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b89400 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287174b30
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871752c0 addr 127.0.0.1 port 123 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871752c0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 39 127.0.0.1:123
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '127.0.0.1' node '127.0.0.1:123'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871752c0 len 20
[15062025 23:17:57] sip /dionaea/sip/__init__.py:568-debug: <dionaea.sip.SipSession object at 0x7f75a1542798> __init__
[15062025 23:17:57] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 88, in __init__
    self._conn = sqlite3.connect(self.users)
sqlite3.OperationalError: unable to open database file
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871761e0 addr 127.0.0.1 port 1883 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871761e0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871761e0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 40 127.0.0.1:1883
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:1883'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b8def0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b8def0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5612871761e0
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287176970 addr 127.0.0.1 port 1900 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287176970
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 41 127.0.0.1:1900
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '127.0.0.1' node '127.0.0.1:1900'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287176970 len 20
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128718bc60 addr 127.0.0.1 port 445 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128718bc60 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128718bc60
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 42 127.0.0.1:445
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:445'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b7e680
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b7e680 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128718bc60
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128718c3f0 addr 127.0.0.1 port 42 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128718c3f0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128718c3f0
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 43 127.0.0.1:42
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:42'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b85fe0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b85fe0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128718c3f0
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128718cb80 addr 127.0.0.1 port 135 iface lo
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128718cb80 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128718cb80
[15062025 23:17:57] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 44 127.0.0.1:135
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:135'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b866a0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b866a0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128718cb80
[15062025 23:17:57] services /dionaea/services.py:34-info: Bind interfaces to address '::1' ...
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128718de30 addr ::1 port 1433 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128718de30 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128718de30
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 45 ::1:1433
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:1433'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b86e40
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b86e40 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128718de30
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128718e5c0 addr ::1 port 27017 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128718e5c0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128718e5c0
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 46 ::1:27017
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:27017'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b87c40
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b87c40 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128718e5c0
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128718ed50 addr ::1 port 3306 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128718ed50 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128718ed50
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 47 ::1:3306
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:3306'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b8fe90
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b8fe90 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128718ed50
[15062025 23:17:57] http /dionaea/http.py:232-debug: http test
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:490-warning: Root path 'var/lib/dionaea/http/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128718f4e0 addr ::1 port 80 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128718f4e0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128718f4e0
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 48 ::1:80
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:80'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b88e90
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b88e90 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x56128718f4e0
[15062025 23:17:57] http /dionaea/http.py:232-debug: http test
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[15062025 23:17:57] http /dionaea/http.py:490-warning: Root path 'var/lib/dionaea/http/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128718fc70 addr ::1 port 443 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x56128718fc70 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128718fc70
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 49 ::1:443
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:443'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection_tls.c:158-debug: connection_tls_mkcert con 0x56128718fc70
[15062025 23:17:57] ftp /dionaea/ftp.py:167-debug: ftp test
[15062025 23:17:57] ftp /dionaea/ftp.py:149-critical: The basedir 'var/lib/dionaea/ftp/root' is not a directory
[15062025 23:17:57] tftp /dionaea/tftp.py:54-critical: Root path 'var/lib/dionaea/tftp/root' is not a directory
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x56128719fb30 addr ::1 port 69 iface lo
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x56128719fb30
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 50 ::1:69
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '::1' node '[::1]:69'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871a02c0 addr ::1 port 1723 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871a02c0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871a02c0
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 51 ::1:1723
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:1723'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286e5ee60
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286e5ee60 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5612871a02c0
[15062025 23:17:57] memcache /dionaea/memcache/__init__.py:45-debug: start memcache
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871a0a50 addr ::1 port 11211 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871a0a50 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871a0a50
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 52 ::1:11211
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:11211'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286d48680
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286d48680 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5612871a0a50
[15062025 23:17:57] printer /dionaea/printer.py:36-critical: The PCL output directory 'var/lib/dionaea/binaries/' is not a directory
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871918a0 addr ::1 port 23 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871918a0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871918a0
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 53 ::1:23
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:23'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286f4e560
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286f4e560 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5612871918a0
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287192030 addr ::1 port 53 iface lo
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287192030
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 54 ::1:53
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '::1' node '[::1]:53'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287192030 len 20
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871927c0 addr ::1 port 53 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871927c0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871927c0
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 55 ::1:53
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:53'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b952d0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b952d0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5612871927c0
[15062025 23:17:57] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287192f50 addr ::1 port 123 iface lo
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287192f50
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 56 ::1:123
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '::1' node '[::1]:123'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287192f50 len 20
[15062025 23:17:57] sip /dionaea/sip/__init__.py:568-debug: <dionaea.sip.SipSession object at 0x7f75a1547f78> __init__
[15062025 23:17:57] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 88, in __init__
    self._conn = sqlite3.connect(self.users)
sqlite3.OperationalError: unable to open database file
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287193e70 addr ::1 port 1883 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287193e70 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287193e70
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 57 ::1:1883
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:1883'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b96b10
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b96b10 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287193e70
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287194600 addr ::1 port 1900 iface lo
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287194600
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 58 ::1:1900
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:297-debug: ip '::1' node '[::1]:1900'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287194600 len 20
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287194d90 addr ::1 port 445 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287194d90 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287194d90
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 59 ::1:445
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:445'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286c703f0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286c703f0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287194d90
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x561287195520 addr ::1 port 42 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x561287195520 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x561287195520
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 60 ::1:42
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:42'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x5612871024d0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x5612871024d0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x561287195520
[15062025 23:17:57] connection /code/src/connection.c:249-debug: connection_bind con 0x5612871aa3b0 addr ::1 port 135 iface lo
[15062025 23:17:57] connection /code/src/connection.c:365-debug: connection_listen con 0x5612871aa3b0 len 20
[15062025 23:17:57] connection /code/src/connection.c:169-debug: bind_local con 0x5612871aa3b0
[15062025 23:17:57] connection /code/src/connection.c:185-debug: bind_local socket 61 ::1:135
[15062025 23:17:57] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[15062025 23:17:57] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[15062025 23:17:57] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:135'
[15062025 23:17:57] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[15062025 23:17:57] incident /code/src/incident.c:376-debug: reporting 0x561286b83ac0
[15062025 23:17:57] incident /code/src/incident.c:365-debug: incident 0x561286b83ac0 dionaea.connection.tcp.listen
[15062025 23:17:57] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5612871aa3b0
[15062025 23:17:57] python /code/modules/python/module.c:303-info: start dionaea.ihandlers 0x561286b92490 0x7f75a2edfc78
[15062025 23:17:57] ihandlers /dionaea/ihandlers.py:36-info: START THE IHANDLERS
[15062025 23:17:57] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.download.offer cb 0x7f75a58838ce ctx 0x7f75a155c348
[15062025 23:17:57] incident /code/src/incident.c:167-debug: ihandler 0x561286c9f080 pattern dionaea.download.offer cb 0x7f75a58838ce ctx 0x7f75a155c348
[15062025 23:17:57] cmd /dionaea/cmd.py:389-debug: cmdshellhandler ready!
[15062025 23:17:57] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.service.shell.* cb 0x7f75a58838ce ctx 0x7f75a155c308
[15062025 23:17:57] incident /code/src/incident.c:167-debug: ihandler 0x561286c25000 pattern dionaea.service.shell.* cb 0x7f75a58838ce ctx 0x7f75a155c308
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:29-debug: logsqlhandler ready!
[15062025 23:17:57] emu /dionaea/emu.py:28-debug: emuprofilehandler ready!
[15062025 23:17:57] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.module.emu.profile cb 0x7f75a58838ce ctx 0x7f75a155c3c8
[15062025 23:17:57] incident /code/src/incident.c:167-debug: ihandler 0x5612871612a0 pattern dionaea.module.emu.profile cb 0x7f75a58838ce ctx 0x7f75a155c3c8
[15062025 23:17:57] store /dionaea/store.py:32-debug: storehandler ready!
[15062025 23:17:57] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.download.complete cb 0x7f75a58838ce ctx 0x7f75a155c588
[15062025 23:17:57] incident /code/src/incident.c:167-debug: ihandler 0x561286cf6960 pattern dionaea.download.complete cb 0x7f75a58838ce ctx 0x7f75a155c588
[15062025 23:17:57] store /dionaea/store.py:26-critical: 'var/lib/dionaea/binaries/' is not a directory
[15062025 23:17:57] incident /code/src/incident.c:178-debug: ihandler_free i 0x561286cf6960
[15062025 23:17:57] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.tftp.tftpdownloadhandler object at 0x7f75a155c348>
[15062025 23:17:57] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.cmd.cmdshellhandler object at 0x7f75a155c308>
[15062025 23:17:57] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.logsql.logsqlhandler object at 0x7f75a155c2c8>
[15062025 23:17:57] incident /code/src/incident.c:165-debug: ihandler_new pattern * cb 0x7f75a58838ce ctx 0x7f75a155c2c8
[15062025 23:17:57] incident /code/src/incident.c:167-debug: ihandler 0x561286e23e90 pattern * cb 0x7f75a58838ce ctx 0x7f75a155c2c8
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:144-info: Getting RPC Services
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:165-info: Setting RPC ServiceOps
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:184-debug: Trying to update table: dcerpcserviceops
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:192-info: ... not required
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:210-debug: Trying to update table: emu_services
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:217-debug: ... not required
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:259-debug: Trying to update table: downloads
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:266-debug: ... not required
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:424-info: Setting MySQL Command Ops
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:578-debug: Updating Table dcerpcs
[15062025 23:17:57] log_sqlite /dionaea/logsql.py:589-debug: ... not required
[15062025 23:17:57] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.emu.emuprofilehandler object at 0x7f75a155c3c8>
[15062025 23:17:57] modules /code/src/modules.c:184-message: start module 0x561286b9cf10
[15062025 23:17:57] dionaea /code/src/dionaea.c:774-info: Installing signal handlers
[15062025 23:17:57] dionaea /code/src/dionaea.c:811-message: Creating 8 threads in pool
[15062025 23:17:57] dionaea /code/src/dionaea.c:825-debug: looping
[15062025 23:29:01] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7f75ac8b18e0 w 0x5612871c9ab0 revents 1024
[15062025 23:29:01] dionaea /code/src/dionaea.c:831-debug: Closing thread pool (8 active threads, 0 jobs in queue), be patient
[15062025 23:29:01] dionaea /code/src/dionaea.c:835-debug: modules free
[15062025 23:29:01] modules /code/src/modules.c:210-message: free module lib/dionaea/curl.so 0x561286b9a670 fn 0x7f75aac2ebb8
[15062025 23:29:01] curl /code/modules/curl/module.c:661-debug: curl_freex
[15062025 23:29:01] modules /code/src/modules.c:210-message: free module lib/dionaea/python.so 0x561286b9c1c0 fn 0x7f75a58813e4
[15062025 23:29:01] python /code/modules/python/module.c:258-debug: freepy /code/modules/python/module.c
[15062025 23:29:01] python /code/modules/python/module.c:270-info: stop dionaea.log 0x561286b917b0 0x7f75a45ffae8
